{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 123", "trace": "self = <wechat.case.test_01.TestLcation object at 0x04CDF910>\n\n    def test_02(self):\n        y = 123\n>       assert 2 == y\nE       assert 2 == 123\n\nwechat\\case\\test_01.py:18: AssertionError"}, "start": 1581756411592, "stop": 1581756411592, "uuid": "4ee0d759-f929-4183-804f-09de5ee3626c", "historyId": "4dc049ce2a6623a30431db2653ba5ca3", "testCaseId": "888eac4c8d9b0b8f12cbfb5a6e6cf362", "fullName": "wechat.case.test_01.TestLcation#test_02", "labels": [{"name": "parentSuite", "value": "wechat.case"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "TestLcation"}, {"name": "host", "value": "GXZ-OFFICE"}, {"name": "thread", "value": "6948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "wechat.case.test_01"}]}